java_binary(
    name = "Main",
    srcs = 
        glob(["src/**/*.java"]),
    deps = [
        "@com_google_guava_guava//jar",
        "@org_json//jar",
        "@javax_inject_javax_inject//jar",
        "@dagger//:dagger_with_compiler",
    ]
)
